### ISSUE TITLE
Assert z 5. cvičení

### ISSUE THREAD

**Issue by HoBi** [tulinkry/teaching-sources#1]
Mohu se zeptat, jaký assert nám na cvičení špatně fungoval (https://github.com/tulinkry/teaching-sources/blob/master/05/month.c#L56-L59)? 

Zkouším tu co všechno ty asserty umí, ale chyba ze cvičení se mi nezobrazí a všechny projdou bez chyby. Byl nějaký assert oproti cvičení smazán? :-)

**Comment by tulinkry** [comment]
Nefungoval nám assert, že rok 2000 není přestupný
```c
assert ( ! isLeapYear ( 2000 ) );
```
Rok 2000 přestupný je. Kód je správně, test byl špatně - [Wikipedie - přestupný rok](https://cs.wikipedia.org/wiki/P%C5%99estupn%C3%BD_rok)

**Comment by HoBi** [comment]
Ahh, jasné. Díky!
